-
  display: Salt Lake City
  name:	west us
  host:	107.182.233.168
  port:	37015
-
  display: Oregon - GCE 1
  name:	west us
  host:	104.198.102.93
  port:	37015
-
  display: Oregon - GCE 2
  name:	west us
  host:	104.198.101.253
  port:	37015
-
  display: Oregon 1
  name:	west us
  host:	52.40.240.176
  port:	37015
-
  display: Oregon 2
  name:	west us
  host:	52.42.44.79
  port:	37015
-
  display: St Louis
  name:	central us
  host:	209.239.121.82
  port:	37015
-
  display: Dallas
  name:	central us
  host:	63.251.239.123
  port:	37015
-
  display: Iowa - GCE 1
  name:	central us
  host:	130.211.193.234
  port:	37015
-
  display: Iowa - GCE 2
  name:	central us
  host:	104.197.17.180
  port:	37015
-
  display: Iowa - GCE 3
  name:	central us
  host:	104.197.136.10
  port:	37015
-
  display: Iowa - GCE 4
  name:	central us
  host:	104.197.42.178
  port:	37015
-
  display: New York
  name:	east us
  host:	107.150.147.67
  port:	37015
-
  display: South Carolina - GCE 1
  name:	east us
  host:	104.196.43.45
  port:	37015
-
  display: South Carolina - GCE 2
  name:	east us
  host:	35.196.104.104
  port:	37015
-
  display: South Carolina - GCE 3
  name:	east us
  host:	104.196.8.33
  port:	37015
-
  display: Virginia 1
  name:	east us
  host:	52.6.64.33
  port:	37015
-
  display: Virginia 2
  name:	east us
  host:	52.86.226.95
  port:	37015
-
  display: Sao Paulo
  name:	brazil south
  host:	177.54.152.31
  port:	37015
-
  display: Sao Paulo - GCE 1
  name:	brazil south
  host:	35.199.89.186
  port:	37015
-
  display: Sao Paulo - GCE 2
  name:	brazil south
  host:	35.199.73.98
  port:	37015
-
  display: Sao Paulo 1
  name:	brazil south
  host:	52.67.92.122
  port:	37015
-
  display: Sao Paulo 2
  name:	brazil south
  host:	52.67.31.204
  port:	37015
-
  display: London
  name:	west europe
  host:	217.147.89.101
  port:	37015
-
  display: Amsterdam
  name:	west europe
  host:	64.95.100.189
  port:	37015
-
  display: Belgium - GCE 1
  name:	west europe
  host:	146.148.120.92
  port:	37015
-
  display: Belgium - GCE 2
  name:	west europe
  host:	104.155.80.155
  port:	37015
-
  display: Belgium - GCE 3
  name:	west europe
  host:	130.211.51.110
  port:	37015
-
  display: Frankfurt 1
  name:	west europe
  host:	52.58.81.34
  port:	37015
-
  display: Frankfurt 2
  name:	west europe
  host:	52.59.121.244
  port:	37015
-
  display: Hong Kong
  name:	east asia
  host:	69.88.135.37
  port:	37015
-
  display: Taiwan - GCE 1
  name:	east asia
  host:	104.155.233.79
  port:	37015
-
  display: Taiwan - GCE 2
  name:	east asia
  host:	104.199.182.138
  port:	37015
-
  display: Singapore 1
  name:	southeast asia
  host:	72.5.161.228
  port:	37015
-
  display: Singapore - GCE 1
  name:	southeast asia
  host:	35.185.189.243
  port:	37015
-
  display: Singapore - GCE 2
  name:	southeast asia
  host:	35.185.189.104
  port:	37015
-
  display: Tokyo
  name:	japan west
  host:	161.202.72.179
  port:	37015
-
  display: Tokyo - GCE 1
  name:	japan west
  host:	104.198.82.36
  port:	37015
-
  display: Tokyo - GCE 2
  name:	japan west
  host:	104.198.82.65
  port:	37015
-
  display: Tokyo - GCE 3
  name:	japan west
  host:	104.198.88.214
  port:	37015
-
  display: Tokyo 1
  name:	japan west
  host:	52.69.157.152
  port:	37015
-
  display: Tokyo 2
  name:	japan west
  host:	52.197.77.217
  port:	37015
-
  display: Sydney
  name:	australia
  host:	27.50.72.162
  port:	37015
-
  display: Sydney - GCE 1
  name:	australia
  host:	35.197.166.13
  port:	37015
-
  display: Sydney - GCE 2
  name:	australia
  host:	35.201.19.135
  port:	37015
-
  display: Sydney 1
  name:	australia
  host:	52.63.136.88
  port:	37015
-
  display: Sydney 2
  name:	australia
  host:	52.62.160.212
  port:	37015
