-
  name: R-99
  damage: 12
  headshot_damage: 18
  legshot_damage: 9.6
  rate_of_fire: 1080
  ammo_capacity: 18
  tactical_reload: 1.8
  empty_reload: 2.45
  ammo_type: light
  projectile_speed: 525
  draw_time: 0.35
  holster_time: 0.3
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_light_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 1x_digital_threat
    stock:
      - standard_stock
  attachments_overwrite:
    extended_light_mag:
      basic:
        ammo_increase: 11%
      rare:
        ammo_increase: 27%
      epic:
        ammo_increase: 50%
  fire_modes:
    auto: true
  spray_pattern:
    starter:
      - x: 50
        y: 120
    follow:
      - x: 5
        y: -6
      - x: 0
        y: -6
      - x: -5
        y: -9
      - x: 3
        y: -4
      - x: 3
        y: -12
      - x: 8
        y: -6
      - x: 4
        y: -10
      - x: 5
        y: -7
      - x: -3
        y: -7
      - x: -4
        y: -5
      - x: -3
        y: -7
      - x: -5
        y: -5
      - x: 2
        y: -9
      - x: 2
        y: -3
      - x: 6
        y: -5
      - x: 7
        y: -2

-
  name: Alternator
  damage: 15
  headshot_damage: 22.5
  legshot_damage: 12
  rate_of_fire: 640
  ammo_capacity: 16
  tactical_reload: 1.9
  empty_reload: 2.23
  ammo_type: light
  projectile_speed: 488
  draw_time: 0.35
  holster_time: 0.3
  available_attachments:
    barrel:
      - barrel_stabilizer
      - flash_hider
    magazine:
      - extended_light_mag
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 1x_digital_threat
    stock:
      - standard_stock
  attachments_overwrite:
    extended_light_mag:
      rare:
        ammo_increase: 45%
      epic:
        ammo_increase: 60%
  fire_modes:
    auto: true
  spray_pattern:
    starter:
      - x: 50
        y: 120
    follow:
      - x: 1
        y: -6
      - x: 3
        y: -4
      - x: -1
        y: -12
      - x: 5
        y: -5
      - x: -7
        y: -7
      - x: 6
        y: -7
      - x: -4
        y: -3
      - x: 7
        y: -5
      - x: -3
        y: -6
      - x: 8
        y: -7
      - x: -5
        y: -5
      - x: 5
        y: -4
      - x: -4
        y: -3
      - x: 3
        y: -3
      - x: -7
        y: -8
-
  name: Prowler
  damage: 14
  headshot_damage: 21
  legshot_damage: 11.2
  rate_of_fire: 800
  ammo_capacity: 20
  tactical_reload: 2.0
  empty_reload: 2.6
  ammo_type: heavy
  projectile_speed: 450
  draw_time: 0.35
  holster_time: 0.3
  available_attachments:
    magazine:
      - extended_heavy_mag
    hop_up:
      - selectfire_receiver
    optics:
      - 1x_hcog_classic
      - 1x_holo
      - 2x_hcog_bruiser
      - 1x-2x_variable_holo
      - 1x_digital_threat
    stock:
      - standard_stock
  attachments_overwrite:
    extended_heavy_mag:
      epic:
        ammo_increase: 75%
  fire_modes:
    burst: 5
    auto: true
  spray_pattern:
    starter:
      - x: 50
        y: 120
    follow:
      - x: -3
        y: -6
      - x: -4
        y: -16
      - x: 4
        y: -5
      - x: 0
        y: -9
      - x: 3
        y: -4
      - x: 1
        y: -7
      - x: -3
        y: -3
      - x: -2
        y: -2
      - x: -5
        y: -4
      - x: -1
        y: -5
      - x: -2
        y: -2
      - x: 0
        y: -2
      - x: 2
        y: -2
      - x: 4
        y: 3
      - x: -5
        y: -9
      - x: 10
        y: -5
      - x: 2
        y: -5
